### ISSUE TITLE
published paper

### ISSUE THREAD

**Issue by XuDongTL** [ethz-asl/laser_slam#29]
Hi there, thanks for contributing your work to the public.
May I know is there any paper to describe your laser slam and sensor fusion that I could refer?

**Comment by rdube** [comment]
Hi @XuDongTL, thanks for your interest. We will be presenting our laser slam system at IROS later this year. Here is a video demonstration: https://www.youtube.com/watch?v=JJhEkIA1xSE and the bib entry:

@inproceedings{dube2017multirobot,
  title={An Online Multi-Robot SLAM System for 3D LiDARs},
  author={Dub{\'e}, Renaud and Gawel, Abel and Sommer, Hannes and Nieto, Juan and Siegwart, Roland and Cadena, Cesar},
  booktitle={{IEEE/RSJ} Int. Conf. on Intelligent Robots and Systems},
  year={2017}
}

If you drop me an email I can send you the paper. rdube (at) ethz.ch

Cheers, 
Renaud

**Comment by XuDongTL** [comment]
Hi Renaud,

Thanks for your prompt reply. The result is very impressive in terms of data association and loop closure, and is even more arresting that it is implemented in multi-agent.

Thanks,
Xudong

**Comment by rdube** [comment]
Thank you! I have sent you the paper. Cheers!

**Comment by 2amour** [comment]
Hi, @rdube ,I have tried both the 2 demonstrations of SegMatch and have read your paper, the demonstrations works really well! Thanks for your fantastic work! But I have some questions about laser_slam, can you send me your paper about laser_slam?

**Comment by rdube** [comment]
Hi @2amour thank you! Here is the paper:

https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=8202268

**Comment by 2amour** [comment]
@rdube Thanks for your prompt reply!You are so kind!

**Comment by JSRGFJZ** [comment]
@2amour Hi, this is Laser_slam, it has some difference with regard to SegMatch.
I don't know if I am wrong that I suppose these are two different algorithms, 
@rdube so what do you think?

**Comment by rdube** [comment]
@JSRGFJZ they are separated. You will find more info in our paper mentioned above.
