### ISSUE TITLE
Launch File

### ISSUE THREAD

**Issue by swarmt** [ethz-asl/laser_slam#31]
Hey There!

Would you mind pushing a launch file?

**Comment by rdube** [comment]
We will push one. In the meantime you can have one of the launch file in our segmatch library which includes our laser_mapper: https://github.com/ethz-asl/segmatch/blob/master/laser_mapper/launch/kitti/kitti_loop_closure.launch

See instructions here: https://github.com/ethz-asl/segmatch/wiki/Demonstrations

**Comment by swarmt** [comment]
Excellent thanks
