### ISSUE TITLE
Laser SLAM build error

### ISSUE THREAD

**Issue by brunoeducsantos** [ethz-asl/laser_slam#38]
Hi,
I was trying to build in a workspace with laser_slam, segmatch and segmatch_ros .
For building I took the following approach:  https://github.com/vkee/segmatch/blob/master/README.md
Although, I am obtaining the following error:

```
In file included from /home/bruno/segmatch_ws/src/laser_slam/laser_slam/include/laser_slam/laser_track.hpp:10:0,
                 from /home/bruno/segmatch_ws/src/laser_slam/laser_slam/src/laser_track.cpp:1:
/home/bruno/segmatch_ws/src/laser_slam/laser_slam/include/laser_slam/common.hpp: In function ‘void laser_slam::correctTransformationMatrix(PointMatcher<float>::TransformationParameters*)’:
/home/bruno/segmatch_ws/src/laser_slam/laser_slam/include/laser_slam/common.hpp:141:75: error: cannot convert ‘std::shared_ptr<PointMatcher<float>::Transformation>’ to ‘PointMatcher<float>::Transformation*’ in initialization
       PointMatcher::get().REG(Transformation).create("RigidTransformation");
                                                                           ^
/home/bruno/segmatch_ws/src/laser_slam/laser_slam/src/laser_track.cpp: In constructor ‘laser_slam::LaserTrack::LaserTrack(const laser_slam::LaserTrackParams&, unsigned int)’:
/home/bruno/segmatch_ws/src/laser_slam/laser_slam/src/laser_track.cpp:33:25: error: cannot convert ‘std::shared_ptr<PointMatcher<float>::Transformation>’ to ‘PointMatcher<float>::Transformation*’ in assignment
   rigid_transformation_ = PointMatcher::get().REG(Transformation).create("RigidTransformation");
                         ^
In file included from /home/bruno/segmatch_ws/src/laser_slam/laser_slam/include/laser_slam/incremental_estimator.hpp:10:0,
                 from /home/bruno/segmatch_ws/src/laser_slam/laser_slam/src/incremental_estimator.cpp:1:
/home/bruno/segmatch_ws/src/laser_slam/laser_slam/include/laser_slam/common.hpp: In function ‘void laser_slam::correctTransformationMatrix(PointMatcher<float>::TransformationParameters*)’:
/home/bruno/segmatch_ws/src/laser_slam/laser_slam/include/laser_slam/common.hpp:141:75: error: cannot convert ‘std::shared_ptr<PointMatcher<float>::Transformation>’ to ‘PointMatcher<float>::Transformation*’ in initialization
       PointMatcher::get().REG(Transformation).create("RigidTransformation");
                                                                           ^
make[2]: *** [CMakeFiles/laser_slam.dir/src/laser_track.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/laser_slam.dir/src/incremental_estimator.cpp.o] Error 1
```

Any help would be appreciated.

Regards,
Bruno

**Comment by brunoeducsantos** [comment]
I found the solution. How can I make a pull request to this repository?
Thanks,
Bruno
@rdube

**Comment by dhananjaisharma10** [comment]
> I found the solution. How can I make a pull request to this repository?
> Thanks,
> Bruno
> @rdube

Hi! I'm facing the same issue. Could you please post the fix over here. Thanks!

**Comment by gpatsiaouras** [comment]
Hi. I am also facing the same issue.
[EDIT] is being fixed in branch fix/pointers2 @dhananjaisharma10

**Comment by pxc2017** [comment]
im facing the same problem,could you please tell me how to solve it thx

**Comment by pxc2017** [comment]
> Hi. I am also facing the same issue.
> 
> [EDIT] is being fixed in branch fix/pointers2 @dhananjaisharma10

Have you solved the problem?plz tell me

**Comment by gpatsiaouras** [comment]
> > Hi. I am also facing the same issue.
> > [EDIT] is being fixed in branch fix/pointers2 @dhananjaisharma10
> 
> Have you solved the problem?plz tell me

Just switch your repo to the branch fix/pointers2

**Comment by pxc2017** [comment]
> Hi. I am also facing the same issue.
> 
> [EDIT] is being fixed in branch fix/pointers2 @dhananjaisharma10

There are three branches,is post-fixes the branch which you mean

**Comment by pxc2017** [comment]
You mean the post-fixes branch?




| |
皮新成
|
|
邮箱：18813127865@163.com
|

签名由 网易邮箱大师 定制

On 05/20/2020 19:31, Giorgos Patsiaouras wrote:

Hi. I am also facing the same issue.
[EDIT] is being fixed in branch fix/pointers2 @dhananjaisharma10

Have you solved the problem?plz tell me

Just switch your repo to the branch fix/pointers2

**Comment by brunoeducsantos** [comment]
Sorry guys, I havent used this repo for so long. I dont remember the fix. Cant help you.
